### ISSUE TITLE
Getting an error message as of the newest version

### ISSUE THREAD

**Issue by myShoggoth** [metal3d/docker-pandoc-server#1]
Not sure why the latest changes in pandoc-server might have affected this, or if it is a Docker thing, but as of the last refresh any attempt to use it with the same parameters as before gives an Python error:

> curl -X POST 127.0.0.1:3801    -d "m=This%20is%20the%20content.&t=Example"
> Something went wrong...'NoneType' object has no attribute 'file'
> 
> curl -X POST 127.0.0.1:3801    -F "m=@README.md"
> Something went wrong...'NoneType' object has no attribute 'file'

**Comment by metal3d** [comment]
Ho my god sorry for that. I will fix it now.

**Comment by metal3d** [comment]
I fixed, I have to rebuild docker image (hub is broken...) and push the image. Thanks for your report

**Comment by metal3d** [comment]
You may pull again the image now, it should be ok

**Comment by myShoggoth** [comment]
Woo hoo!
